# Generated by Django 2.2 on 2022-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
